# Generated by Django 4.2.30 on 2026-05-16 20:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_age', models.IntegerField()),
                ('customer_sex', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField()),
                ('allowed_gender', models.CharField(blank=True, max_length=3, null=True)),
                ('is_adult_only', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'product',
                'ordering': ['product_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('bill_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='store.customer')),
            ],
            options={
                'db_table': 'bill',
                'ordering': ['-bill_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('bill_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'db_table': 'billitem',
                'managed': True,
            },
        ),
    ]
