# Generated by Django 4.2.30 on 2026-05-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Upload hero slideshow image (recommended size: 1200x400px)', upload_to='hero_images/')),
                ('title', models.CharField(blank=True, help_text='Optional title for the slide', max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle for the slide', max_length=200, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hero_image',
                'ordering': ['order', 'uploaded_at'],
                'managed': True,
            },
        ),
    ]
