# Generated by Django 4.2.30 on 2026-05-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_heroimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLogin',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='store.customer')),
            ],
            options={
                'db_table': 'customer_login',
                'ordering': ['-login_time'],
                'managed': True,
            },
        ),
    ]
